apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: globex-partner-gateway-backend
spec:
  name: "Globex Partner Gateway Backend"
  systemName: "globex-partner-gateway-backend"
  privateBaseURL: "http://globex-partner-gateway.globex-apim-user1.svc.cluster.local:8080"
  providerAccountRef:
    name: 3scale-tenant-secret
