apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: globex-mobile-gateway-backend
spec:
  name: "Globex Mobile Gateway Backend"
  systemName: "globex-mobile-gateway-backend"
  privateBaseURL: "http://globex-mobile-gateway.globex-apim-user1.svc.cluster.local:8080"
  providerAccountRef:
    name: 3scale-tenant-secret
