apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: globex-partner-gateway-product
spec:
  name: "Globex Partner Gateway Product"
  systemName: "globex-partner-gateway-product"
  backendUsages:
    globex-partner-gateway-backend:
      path: /