apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: globex-mobile-gateway-backend
spec:
  name: "Globex Mobile Gateway Backend"
  systemName: "globex-mobile-gateway-backend"
  privateBaseURL: "<change-me>"
  providerAccountRef:
    name: user1-3scale-tenant-secret
