apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: admin.mobile
spec:
  username: admin.mobile
  email: admin@mobile.com
  passwordCredentialsRef:
    name: mobileuser.secret
  role: admin
  developerAccountRef:
    name: mobile-developeraccount
  providerAccountRef:
    name: 3scale-tenant-secret

---


apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: dev.mobile
spec:
  username: dev.mobile
  email: dev@globex.com
  passwordCredentialsRef:
    name: mobileuser.secret
  role: member
  developerAccountRef:
    name: mobile-developeraccount
  providerAccountRef:
    name: 3scale-tenant-secret